on: workflow_dispatch
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install yarn -g
        run: npm install yarn -g
      - name: yarn install
        run: yarn
      - name: yarn build
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: packages/shell-chrome
